name: Library Publish PCM

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest Release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          repository: ${{ github.repository }}

      - name: Create pull request to KiCad repository
        permission: write-all
        run: gh pr create -B main -H not-main --title "merge not-main to main" --body "Created by github action"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
