name: Library Publish PCM

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest Release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          repository: ${{ github.repository }}

      - name: Create pull request to KiCad repository
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          base: main
          branch: not-main
